apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: kibana
    annotations:
        kubernetes.io/ingress.class: traefik
        ingress.kubernetes.io/auth-type: "basic"
        ingress.kubernetes.io/auth-secret: kibana-basic-auth
spec:
    rules:
      - http:
          paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: http