apiVersion: v1
kind: Service
metadata:
  name: boilerplate-frontend
  labels:
    app: boilerplate-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: fe-port
      protocol: TCP
      name: fe-lb
  selector:
    app: boilerplate-frontend

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
data:
  be.url: a346d7b6fb01e11e89a570ad58844c9c-91072408.us-east-1.elb.amazonaws.com

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplate-frontend
  labels:
    app: boilerplate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-frontend
  template:
    metadata:
      labels:
        app: boilerplate-frontend
    spec:
      containers:
        - name: boilerplate-frontend
          image: 125181119024.dkr.ecr.us-east-1.amazonaws.com/boilerplate:v13
          env:
            - name: BE_URL
              valueFrom:
                configMapKeyRef:
                  name: be-config
                  key: be.url
          ports:
            - name: fe-port
              containerPort: 3000
              protocol: TCP