apiVersion: v1
kind: Service
metadata:
  name: boilerplate-frontend
  labels:
    app: boilerplate-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: boilerplate-frontend
  selector:
    app: boilerplate-frontend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplate-frontend
  labels:
    app: boilerplate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-frontend
  template:
    metadata:
      labels:
        app: boilerplate-frontend
    spec:
      containers:
        - name: boilerplate-frontend
          image: 125181119024.dkr.ecr.us-east-1.amazonaws.com/boilerplate:v2
          env:
          - name: BE_URL
            value: "http://aec352f51ac2911e8b85a0aea3d51daf-2132069829.us-east-1.elb.amazonaws.com"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP