apiVersion: v1
kind: Service
metadata:
  name: boilerplate-backend
  labels:
    app: boilerplate-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: be-port
      protocol: TCP
      name: be-lb
  selector:
    app: boilerplate-backend

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplate-backend
  labels:
    app: boilerplate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boilerplate-backend
  template:
    metadata:
      labels:
        app: boilerplate-backend
    spec:
      containers:
        - name: boilerplate-be
          image: 125181119024.dkr.ecr.us-east-1.amazonaws.com/boilerplate-backend:v6
          command: ["/bin/sh"]
          args: ["-c", "yarn start"]
          ports:
            - name: be-port
              containerPort: 4500
              protocol: TCP
          volumeMounts:
            - mountPath: "/backend/logs"
              name: efs-boilerplate-vol
            - mountPath: /backend/logs
              name: backendlogs
      volumes:
        - name: efs-boilerplate-vol
          persistentVolumeClaim:
            claimName: efs-boilerplate-claim
            volumes:
        - name: backendlogs
          hostPath:
            path: /backend/logs
