apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-boilerplate
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-87a23bcc.efs.us-east-1.amazonaws.com
    path: "/"